### ISSUE TITLE
Does not function with Django 3.0

### ISSUE THREAD

**Issue by matthew-nm** [LegoStormtroopr/django-spaghetti-and-meatballs#31]
I am using the latest version on PyPi (0.2.2) with Django 3.0.9 and Python 3.8.5. 

In the latest Django the 'url' function is replaced by 'path', so my urls.py looks as follows,
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('plate/', include('django_spaghetti.urls')),
]
```

When I go to plate/ on my webserver, I get the following error,
```
Internal Server Error: /plate/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django_spaghetti/views.py", line 40, in get
    return self.plate()
  File "/usr/local/lib/python3.8/site-packages/django_spaghetti/views.py", line 85, in plate
    if f.rel is not None:
AttributeError: 'AutoField' object has no attribute 'rel'
[06/Aug/2020 22:35:31] "GET /plate/ HTTP/1.1" 500 81752
```

Is this a configuration issue, or a bug? Does this package get updated on PyPi when there are updates? I am using this with Docker, so being able to access via `pip` is great.

Thanks!

**Comment by LegoStormtroopr** [comment]
Thanks for reporting this @matthew-nm I'll have a look this weekend.

**Comment by namdyny** [comment]
@matthew-nm 
Hope you have figured out the solution. I had encounter the same problem and I managed it by pip installing directly from the master branch of this github:
`pip install https://github.com/LegoStormtroopr/django-spaghetti-and-meatballs/archive/master.zip`

**Comment by LegoStormtroopr** [comment]
Version 0.3.0 is now on PyPI 🤯

**Comment by LegoStormtroopr** [comment]
Thanks everyone for prodding me about this
