### ISSUE TITLE
File not found: delete.png

### ISSUE THREAD

**Issue by benman1** [LegoStormtroopr/django-spaghetti-and-meatballs#4]
...
The CSS file 'django_spaghetti/vis.min.css' references a file which could not be found:
  django_spaghetti/img/timeline/delete.png

Complete traceback when starting django: 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/Users/benjamin/reporting/venv/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
    raise processed
whitenoise.django.MissingFileError: The file 'django_spaghetti/img/timeline/delete.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x105534650>.
```

**Comment by benman1** [comment]
I went about downloading some image files for a fast fix, and I noticed that there are many more pngs missing...

**Comment by LegoStormtroopr** [comment]
Ah, this was cause by the fact my own instance was using the CDN version of Vis.js. I'll fix this soon in the next version.

The solution will probably be a bundled version of Vis.js, with a ``settings`` option to declare where to load it from.

In the interim, you can probably just delete everything in the `django_spaghetti/static/django_spaghetti` and use the CDN version for the time being: http://cdnjs.com/libraries/vis

Thanks!

**Comment by benman1** [comment]
Thanks for getting back to me, much appreciated. Django doesn't complain anymore. I've cloned from https://github.com/almende/vis, then copied the vis/dist/img/ directory to my virtual environment into venv/lib/python2.7/site-packages/django_spaghetti/static/django_spaghetti/.
